#spring:
#  main:
#    banner-mode: console
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/orangeCms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234qwer!
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
  banner:
    location: banner.txt

#logging:
#  file:
#    name: myApplication.log
#  level:
#    org.hibernate.type.descriptor.sql.BasicBinder : trace

#logging:
#  config: classpatch: log4j2.yml


server:
  port: 8080

#日志配置 无特殊需求无需更改
logging:
  config:  classpath:log4j2.yml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG






