#spring:
#  main:
#    banner-mode: console
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orangeCms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234qwer!
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
  banner:
    location: banner.txt

server:
  port: 8080

logging:
  config: classpath:log4j2.yml



#logging:
#  level:
#    org.springframework.security:
#      - debug
#      - info
#    org.springframework.web: error
#    org.hibernate.SQL: debug
#    org.hibernate.engine.QueryParameters: debug
#    org.hibernate.engine.query.HQLQueryPlan: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace






